[package]
name = "lazy"
version = "0.1.0"
edition = "2024"

[dependencies]
aster = { version = "0.1.0", path = "aster" }
compiler = { version = "0.1.0", path = "compiler" }
gluezy = { version = "0.1.0", path = "gluezy" }
lang = { version = "0.1.0", path = "lang" }
log = { version = "0.1.0", path = "log" }
