mod numeric;
mod token;
mod state;
pub mod bufreader;

use std::{collections::VecDeque, io::Read};

use lang::{Compiler, token::Token, span::{Position, Span}};
use string_pool::StringPool;

use crate::{state::State, token::TokenSpan};
use crate::bufreader::BufferedUtf8MetadataReader;

#[derive(Debug)]
pub struct Tokenizer<'pool, C: Compiler, const N: usize, T: Read> {
  /// The [`StringPool`] that stores all of our identifiers and maps them to a
  /// [`Copy`] unique key.
  pool: &'pool StringPool,
  /// [`ModuleReference`] to [`crate::lang::module::Module`] that is the root
  /// of that source file, i.e. has a [`std::path::Path`] for
  /// [`crate::lang::module::ModuleParent`].
  module: C::ModuleReference,
  /// The name of this module for debugging purposes.
  name: String,
  /// A special reader that tracks line, column, position, and parses UTF-8 with
  /// a buffer in between.
  meta_reader: BufferedUtf8MetadataReader<N, T>,
  /// The current parse state of the parser.
  state: State,
  /// The next character, if one is already read, but not yet processed.  This
  /// usually happens after a [`State`] change.
  next: Option<char>,
  /// The tokens generated by the parser.  The parser may spit out more than one
  /// [`TokenSpan`] at a time, so we queue them here.
  toks: VecDeque<TokenSpan<C>>,
  /// The current indentation of the parser.
  /// TODO: why is this here?  We can't use [`crate::aster::bufreader::Metadata::whitespace`]?
  indentation: isize,
  /// If the parser has finished, meaning the special end token has been returned.
  ended: bool,
  last_span: Span<C>,
  /// This is a bandaid to fix an issue with multiline comments having indentation
  /// inside them.
  override_indentation: Option<usize>,
}

pub type Error<C> = lang::error::TokenError<C>;

impl<'a, C: Compiler, const N: usize, T: Read> Iterator for Tokenizer<'a, C, N, T> {
  type Item = Result<TokenSpan<C>, Error<C>>;

  fn next(&mut self) -> Option<Self::Item> {
    let result = self.do_state();

    if let Some(Ok((_, span))) = result {
      self.last_span = span;
    };

    result.or_else(|| self.end_indent())
  }
}

impl<'pool, C: Compiler, const N: usize, T: Read> Tokenizer<'pool, C, N, T> {
  pub fn new(
    pool: &'pool StringPool,
    module: C::ModuleReference,
    name: String,
    meta_reader: BufferedUtf8MetadataReader<N, T>,
  ) -> Self {
    let start_and_end = Position::default();

    Self {
      pool,
      module,
      name,
      meta_reader,
      state: State::Base,
      next: None,
      toks: VecDeque::new(),
      indentation: 0,
      ended: false,
      last_span: Span {
        module,
        start: start_and_end,
        end: start_and_end,
      },
      override_indentation: None,
    }
  }

  fn end_indent(&mut self) -> Option<Result<TokenSpan<C>, Error<C>>> {
    if self.ended {
      None
    } else {
      self.ended = true;
      let mut span = self.last_span;
      span.start.indentation = 0;
      span.end.indentation = 0;
      Some(Ok((Token::Indent(-self.indentation), span)))
    }
  }

  fn take_ch(&mut self) -> Result<Option<char>, Error<C>> {
    if let Some(next) = self.next.take() {
      return Ok(Some(next));
    };

    match self.meta_reader.next() {
      Some(Ok(ch)) => Ok(Some(ch)),
      Some(Err(_)) => Err(Error::IO {
        name: self.name.to_owned(),
        module: self.module,
      }),
      None => Ok(None),
    }
  }

  fn save(&mut self, ch: char) {
    assert!(self.next.is_none());

    self.next = Some(ch);
  }

  fn retry(&mut self, ch: char, state: State) {
    self.save(ch);
    self.state = state;
  }

  fn push_here(&mut self, tok: Token, start: Position) {
    let span = Span {
      start,
      end: self.pos(),
      module: self.module,
    };
    self.toks.push_back((tok, span));
  }

  fn next_pos(&mut self) -> Result<Position, Error<C>> {
    if let Some(ch) = self.take_ch()? {
      self.save(ch);
    };

    Ok(self.pos())
  }

  fn pos(&self) -> Position {
    (&self.meta_reader.meta).into()
  }
}
