[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_macros = { version = "0.1.0", path = "../lazy_macros" }
string_pool = { version = "0.1.0", path = "../string_pool" }
log = { version = "0.1.0", path = "../log" }
pprint = { version = "0.1.0", path = "../pprint" }
lang = { version = "0.1.0", path = "../lang" }
tokenize = { version = "0.1.0", path = "../tokenize" }
gluezy = { version = "0.1.0", path = "../gluezy" }
resolve = { version = "0.1.0", path = "../resolve" }
generate = { version = "0.1.0", path = "../generate" }
