[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
cc = "1.2.58"
string_pool = { version = "0.1.0", path = "../string_pool" }
inkwell = { version = "0.8.0", features = ["llvm18-1"] }
tempfile = "3.27.0"
lang = { version = "0.1.0", path = "../lang" }
tokenize = { version = "0.1.0", path = "../tokenize" }
gluezy = { version = "0.1.0", path = "../gluezy" }
lazy_macros = { version = "0.1.0", path = "../lazy_macros" }
pprint = { version = "0.1.0", path = "../pprint" }
log = { version = "0.1.0", path = "../log" }
resolve = { version = "0.1.0", path = "../resolve" }
